### ISSUE TITLE
Users can change the color scheme of the page

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/code-journal#11]
## 💰 Motivation

If a user wants to change the colors, they can select from a drop down menu

## 📐 Plan

Provide a drop down that users can use to change the colors

## ✅ Task List

- [x] Create a drop down menu of colors
- [x] Create an event listener for when a color is selected
- [x] Show the DOM tree with only dates selected
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
