### ISSUE TITLE
User can search their entries

### ISSUE THREAD

**Issue by JihengNie** [JihengNie/code-journal#9]
## 💰 Motivation

If a user wants to find a certain entry, they can search for it by title

![image](https://user-images.githubusercontent.com/109745413/190281513-14c52b6f-2c77-4e46-991c-d8b650b10a4a.png)

## 📐 Plan

Provide a search box that causes the entries list to only show title that matches.

## ✅ Task List

- [x] Create a search box by the entries header and a search button
- [x] Create an event listener for the keys entered
- [x] Check if the searched text is contained in the title of the entries. 
- [x] If yes, add an is-in search-bar attribute to the 'li' element with a true value, otherwise, give it false.
- [x] Show the DOM tree with only is-in-search-bar attribute of true
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
